version: "3.5"

services:
  db-server:
    image: mysql:latest
    container_name: db-server
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - apache-mysql-php

  web-server:
    build: ./
    image: apache-php
    container_name: web-server
    restart: always
    depends_on:
      - db-server
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 80:80
    networks:
      - apache-mysql-php

volumes:
  mysql-volume:
    name: mysql-volume

networks:
  apache-mysql-php:
    name: apache-mysql-php
    driver: bridge
